# dataflyten til programmet er representert ved bruk av utskriftsfunksjoner

from dato import Dato

def hovedprogram():
# lage en instansklasse (objekt) ved å gi den tre argumenter
    today = Dato(5,10,2024)
    print('----------')
    print('viser året')
    print('----------')
    print()
    print(today.hent_aar())
    print()
    print('------------')
    print('viser datoen')
    print('------------')
    print()
    print(today.return_datos())
    print()
    print('---------------------------------------------------------------------------------------')
    print('sjekk om dagen jeg la inn som inndata tilsvarer dagen på den tidligere innstilte datoen')
    print('---------------------------------------------------------------------------------------')
    print()
    print(today.day_check(4))
    print()
    print(today.day_check(5))
    print()
    print('-----------------------------------')
    print('legge til én dag til gjeldende dato')
    print('-----------------------------------')
    print()
    today.nyy_dag()
    print(today.return_datos())
    print()
    print('----------------------------------')
    print('sjekke om datoer er før 6.10.2024')
    print('----------------------------------')
    print()
    print(today.kommer_foer('4.9.2024'))
    print()
    print(today.kommer_foer('4.11.2024'))
    print()
    print(today.kommer_foer('6.10.2024'))

hovedprogram()
